version: '3.8'

services:
  jamtem-world-site:
    image: jamtem/jamtem-world-site:latest
    container_name: jamtem-world-site
    ports:
      - "8000:8000"
    environment:
      # Shopify Configuration
      - SHOPIFY_STORE_DOMAIN=${SHOPIFY_STORE_DOMAIN}
      - SHOPIFY_STOREFRONT_ACCESS_TOKEN=${SHOPIFY_STOREFRONT_ACCESS_TOKEN}
      - SHOPIFY_API_VERSION=${SHOPIFY_API_VERSION}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      
      # Airtable Configuration
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
      - AIRTABLE_TABLE_ID=${AIRTABLE_TABLE_ID}
      
      # Cloudinary Configuration
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: jamtem-network
